macro(add_include_directories TARGET_NAME ACCESS PATH)
  file(GLOB SUBDIRECTORIES LIST_DIRECTORIES ON ${PATH}/*)
  foreach(DIRECTORY ${SUBDIRECTORIES})
    if(IS_DIRECTORY ${DIRECTORY})
      target_include_directories(${TARGET_NAME} ${ACCESS} ${DIRECTORY})
    endif()
  endforeach()
endmacro()
